project/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.MonthCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/',
         views.MonthCalendar.as_view(), name='month'),
    path(
        'month_with_schedule/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),
    path(
        'month_with_schedule/<int:year>/<int:month>/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
    ),
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path(
        'mycalendar/<int:year>/<int:month>/<int:day>', views.MyCalendar.as_view(), name='mycalendar'
    ),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

project/app/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Cost(models.Model):
    """その日の費用、naritoではスケジュールとして扱われている"""
    summary = models.CharField('カテゴリ', max_length=30)
    money = models.IntegerField(
        '金額', validators=[MinValueValidator(0), MaxValueValidator(100000000)])
    description = models.TextField('詳細な説明', blank=True)
    date = models.DateField('日付', default=timezone.now)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

project/app/forms.py
from django import forms
from .models import Cost


class BS4CostForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Cost
        # Costで表示するフィールド、'__all__'とすると全て
        fields = ('summary', 'money', 'description')
        # widget = {‘事前に設定をしたクラスのfield’:forms.TextInput等(attrs={‘class’: ‘cssのclass名’})}
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'money': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
        }

    def clean_money(self):
        dt_money = self.cleaned_data.get('money')
        if 0 > dt_money:
            raise forms.ValidationError('それやと増えとるがな')
        return self.cleaned_data.get('money')

project/app/views.py
from django.views import generic
from . import mixins
from .models import Cost
import datetime
from django.shortcuts import redirect
from .forms import BS4CostForm


class MonthCalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'app/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class MonthWithScheduleCalendar(mixins.MonthWithScheduleMixin, generic.TemplateView):
    """費用付きの月間カレンダーを表示するビュー"""
    template_name = 'app/month_with_schedule.html'
    model = Cost
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class WeekWithScheduleCalendar(mixins.WeekWithScheduleMixin, generic.TemplateView):
    """スケジュール付きのカレンダーを表示するビュー"""
    template_name = 'app/week_with_schedule.html'
    model = Cost
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        caledar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面"""
    template_name = 'app/mycalendar.html'
    model = Cost
    date_field = 'date'
    form_class = BS4CostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(
                year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('app:mycalendar', year=date.year, month=date.month, day=date.day)

project/app/templates/app/base.html
<!doctype html>
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>家計簿</title>
</head>

<body>

    <div class="container" mt-3>
        {% block content %}{% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <!--JavaScriptを書くときの定義-->
    {% block extrajs %}{% endblock %}
</body>

</html>

project/app/templates/app/month.html
{% extends 'app/base.html' %}

{% block content %}
<a href="{% url 'app:month' month_previous.year month_previous.month %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'app:month' month_next.year month_next.month %}">次月</a>

<table class="table">
    <thead>
        <tr>
            {% for w in week_names %}
            <th>{{ w }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for week in month_days %}
        <tr>
            {% for day in week %}
            {% if now == day %}
            <td class="table-success">
                {% else %}
            <td>
                {% endif %}

                {% if month_current.month != day.month %}
                {{ day | date:"m/d" }}
                {% else %}
                {{ day.day }}
                {% endif %}

            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

project/app/templates/app/month2.html
<a href="{% url 'app:mycalendar' month_previous.year month_previous.month month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'app:mycalendar' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
        <tr>
            {% for w in week_names %}
            <th>{{ w }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for week in month_days %}
        <tr>
            {% for day in week %}
            {% if now == day %}
            <td class="table-success">
                {% else %}
            <td>
                {% endif %}

                <a href="{% url 'app:mycalendar' day.year day.month day.day %}">{{ day.day }}</a>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

project/app/templates/app/month_with_schedule.html
{% extends 'app/base.html' %}
{% block content %}
<style>
    table {
        table-layout: fixed;
    }

    td>div {
        height: 100px;
        overflow: hidden;
        white-space: nowrap;
    }
</style>

<a href="{% url 'app:month_with_schedule' month_previous.year month_previous.month %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'app:month_with_schedule' month_next.year month_next.month %}">次月</a>
<table class="table">
    <thead>
        <tr>
            {% for w in week_names %}
            <th>{{ w }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for week_day_schedules in month_day_schedules %}
        <tr>
            {% for day, schedules in week_day_schedules.items %}
            {% if now == day %}
            <td class="table-success">
                {% else %}
            <td>
                {% endif %}

                <div>
                    {% if month_current.month != day.month %}
                    <!-- 先月分の日付表示 -->
                    {{ day | date:"m/d" }}
                    {% else %}
                    <!-- 今月分の日付表示 -->
                    {{ day.day }}
                    {% endif %}

                    {% for schedule in schedules %}
                    <p>{{ schedule.summary }}</p>
                    {% endfor %}
                </div>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

project/app/templates/app/mycalendar.html
{% extends 'app/base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-3">
        {% include 'app/month2.html' %}
        <hr>
        <!--
            action属性はどこにデータを送信するのかを定義する
            値は相対、絶対URL出なければならない
            もし送信先が定義されていないなら、
            フォームが表示されているページ自身に対してデータ送信を行う

            method属性はデータの転送方法のこと
            getはURLに入力内容を合わせて送信されるので、
            断片的な情報を伝達するには適している
            postはURL表示欄には表示せずに送信されるので、
            機密性のある長文には適してる
        -->
        <form action="" method="POST">
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="form-group row">
                <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label_tag }}</label>
                <div class="col-sm-8">
                    {{ field }}
                    {{ field.errors }}
                </div>
            </div>
            {% endfor %}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-block">送信</button>
        </form>
    </div>
    <div class="col-md-9">
        {% include 'app/week.html' %}
    </div>

</div>
{% endblock %}

project/app/templates/app/week.html
<a href="{% url 'app:mycalendar' week_previous.year week_previous.month  week_previous.day %}">前週</a>
{{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
<a href="{% url 'app:mycalendar' week_next.year week_next.month  week_next.day %}">次週</a>

<table class="table" style="table-layout: fixed;">
  <tbody>
    <tr>
      {% for day in week_days %}
      {% if now == day %}
      <td class="table-success">
        {% else %}
      <td>
        {% endif %}
        {% if week_first.month != day.month %}
        {{ day | date:"m/d" }}
        {% else %}
        {{ day.day }}
        {% endif %}
      </td>
      {% endfor %}
    </tr>
    <tr>
      {% for schedules in week_day_schedules.values %}
      <td>
        {% for s in schedules %}
        {{ s.summary }}<br>
        {{ s.money }}<br>
        {{ s.description | linebreaks }}
        {% endfor %}
      </td>
      {% endfor %}
    </tr>
  </tbody>
</table>